title: Marco's GitHub Pages.
description: Welcome to Marco's GitHub Pages.
google_analytics: false
show_downloads: true
encoding: utf-8
#markdown: markdown
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
